const fs = require('fs');
const path = require('path');

function convertToEmbeddedLink(oldLink: string): string {
    try {
        const url = new URL(oldLink.trim());
        
        // Force domain to twitter.com
        url.hostname = 'twitter.com';
        
        // Add the ref_src parameter
        url.searchParams.set('ref_src', 'twsrc%5Etfw');
        
        return url.toString();
    } catch (error) {
        console.error(`Error processing link: ${oldLink}`);
        throw error;
    }
}

function main(): void {
    const inputFile = path.join(process.cwd(), 'old.txt');
    const outputFile = path.join(process.cwd(), 'lib', 'all-tweets.ts');

    try {
        // Read input file with new links
        const inputContent = fs.readFileSync(inputFile, 'utf-8');
        const newLinks: string[] = inputContent.split('\n').filter((line: string) => line.trim());
        const convertedNewLinks: string[] = newLinks.map((link: string) => convertToEmbeddedLink(link));

        // Read existing all-tweets.ts file
        let existingContent = '';
        try {
            existingContent = fs.readFileSync(outputFile, 'utf-8');
        } catch (error) {
            // If file doesn't exist, create it with empty array
            existingContent = 'export const allTweets = [];\n';
        }

        // Extract existing links
        const match = existingContent.match(/export const allTweets = \[([\s\S]*?)\];/);
        const existingLinksText = match ? match[1].trim() : '';
        const existingLinks = existingLinksText
            ? existingLinksText.split('\n').map(line => line.trim()).filter(line => line.endsWith(','))
            : [];

        // Combine existing and new links
        const combinedLinks = [
            ...existingLinks,
            ...convertedNewLinks.map(link => `  "${link}",`)
        ];

        // Generate the output content
        const outputContent = `// Auto-generated by convert-tweets.ts
export const allTweets = [
${combinedLinks.join('\n')}
];
`;

        // Write to all-tweets.ts
        fs.writeFileSync(outputFile, outputContent, 'utf-8');
        console.log(`Successfully added ${convertedNewLinks.length} new tweets to all-tweets.ts`);

    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
}

main(); 